import type { Metadata } from "next";
import "./globals.css";

import * as fonts from "./fonts";

export const metadata: Metadata = {
  title: "Cook Book",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fonts.handwriting.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
